[dist]
# The name of your project
name = "graff"

# The version of your project (this will be automatically updated)
version = "0.1.0"

# The description of your project
description = "A powerful command-line chart generation tool written in Rust"

# The license of your project
license = "MIT"

# The repository URL
repository = "https://github.com/your-username/graff"

# The homepage URL
homepage = "https://github.com/your-username/graff"

# The documentation URL
documentation = "https://github.com/your-username/graff#readme"

# The keywords for your project
keywords = ["charts", "visualization", "cli", "data", "rust"]

# The categories for your project
categories = ["command-line-utilities", "data-visualization"]

# The authors of your project
authors = ["Your Name <your.email@example.com>"]

# The readme file
readme = "README.md"

# The targets to build
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "x86_64-pc-windows-msvc",
]

# The artifacts to include
artifacts = [
    "graff",
]

# The files to include in the distribution
include = [
    "README.md",
    "LICENSE",
    "docs/",
    "charts/",
    "scripts/",
]

# The files to exclude from the distribution
exclude = [
    "target/",
    "tests/",
    ".git/",
    ".github/",
    "*.png",
    "*.jpg",
    "*.jpeg",
    "*.gif",
    "*.svg",
]

# The compression format
compression = "gzip"

# Whether to sign the release
sign = false

# The GitHub release settings
[dist.github]
# The repository owner
owner = "your-username"
# The repository name
repo = "graff"
# Whether to create a draft release
draft = false
# Whether to prerelease
prerelease = false

# The release notes template
[dist.github.release-notes]
# The template for the release notes
template = """
# Graff v{version}

## What's Changed

{changelog}

## Installation

Download the appropriate binary for your platform from the assets below.

## Usage

```bash
# Basic usage
graff line --input data.csv --x date --y value --title "My Chart"

# With theme
graff bar --input data.csv --x category --y value --theme dark

# See all options
graff --help
```

## Supported Chart Types

- Line Charts
- Area Charts  
- Bar Charts
- Stacked Bar Charts
- Heatmaps
- Scatter Plots
- Funnel Charts
- Retention Charts

## Themes

All charts support both light and dark themes for different presentation contexts.

## Documentation

See the [examples](docs/examples.md) for comprehensive usage examples.
"""

# The changelog settings
[dist.changelog]
# The changelog file
file = "CHANGELOG.md"
# The format of the changelog
format = "markdown"
# The sections to include
sections = [
    "Features",
    "Bug Fixes", 
    "Breaking Changes",
    "Documentation",
    "Other",
]
