name: Generate Chart Examples

on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]
  workflow_dispatch:

jobs:
  generate-examples:
    runs-on: ubuntu-latest
    env:
      RUST_FONTCONFIG_DLOPEN: "1"
      FONTCONFIG_NO_PKG_CONFIG: "1"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libfontconfig1-dev pkg-config
        
    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
          
    - name: Build Graff
      run: cargo build --release
      
    - name: Clear charts directory
      run: |
        rm -rf charts/*
        mkdir -p charts
        
    - name: Generate chart examples
      run: |
        chmod +x scripts/generate-examples.sh
        ./scripts/generate-examples.sh
        
    - name: Generate documentation
      run: |
        chmod +x scripts/generate-docs.sh
        ./scripts/generate-docs.sh
        
    - name: Commit and push changes
      if: github.ref == 'refs/heads/prod'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add charts/ docs/examples.md
        git diff --quiet && git diff --staged --quiet || git commit -m "Update chart examples and documentation"
        git push
